### ISSUE TITLE
Error: In imhof(n * omega.hat.2, lamstar^2) : Note that Qq + abserr is positive.

### ISSUE THREAD

**Issue by proshano** [qpsy/nonnest2#3]
Hello and thank you for making this package.

I am using it to calculate confidence intervals but am encountering the following error, along with a p-value <0.05 and a 95% CI for AIC that just crosses 0. I wonder if the two are related.

Thank you

**Comment by ecmerkle** [comment]
Could you post the specific command(s) that lead to that message? I believe it is a warning, as opposed to an error, and it is related to the way that probabilities from the null distribution are being approximated (using the CompQuadForm package). I have previously seen the message and obtained reasonable results, though of course cannot guarantee that will always be true.

**Comment by proshano** [comment]
you’re right, it is a warning

It happens when i do this and not with all model objects.

vuongtest(model1, model2)

**Comment by ecmerkle** [comment]
Ok, that makes sense. I don't think that the conflicting p<.05 and 95% AIC CI indicate a problem by themselves, because the vuongtest() statistic does not involve the AIC penalty terms by default. A better comparison would be

`vuongtest(model1, model2, adj="aic")`

which includes the aic penalty in the test statistic computation.

I believe that the other warning is indicating that the approximation of the null distribution is not great. I cannot say for sure whether it is a problem, and I don't have an alternative solution if it is a problem. Perhaps you would have luck asking the CompQuadForm developer.

**Comment by proshano** [comment]
Thank you for your help!

I did try adj=“aic” and it makes no difference.

**Comment by ecmerkle** [comment]
I would guess that model1 and model2 have the same number of parameters, so that their aic penalties cancel for you. But if you are able to share data/code, I could look some more.

**Comment by proshano** [comment]
This is true - same # of parameters.

Unfortunately the data are confidential and I am not able to share.

Thank you for your help and your package

**Comment by proshano** [comment]
p is <0.00001 for distinguishability; its the second pvalue that is just significant at p=0.027 and 95% CI just clips 0 on the upper bound (+0.43).

**Comment by ecmerkle** [comment]
Oh, I think it is a one- vs two-tailed test thing. The non-nested LRT gives you two one-tailed p-values, one p-value for Model 1 fitting better than Model 2 and one p-value for the opposite. You would double the smaller of the two for the "two-tailed" p-value that would be comparable to the CI. So I think you have 2*.027 = .054, which matches the CI.

**Comment by proshano** [comment]
it dawned on me maybe 2 seconds before your email popped in!
