### ISSUE TITLE
Vuong test with MLR estimator

### ISSUE THREAD

**Issue by isaactpetersen** [qpsy/nonnest2#4]
Thanks for your development of this package! I was wondering whether there is any interest/plans for extending the Vuong test in the package to allow models that have been estimated with robust standard errors to account for non-normally distributed data (e.g., the `MLR` estimator in lavaan)?

**Comment by ecmerkle** [comment]
I think this is tricky because robust SEs are corrections to the SEs of a model that is already estimated, and the Vuong test is applied directly to pieces of the estimated models. So my thought is that one could apply Vuong tests to models estimated under ML, even if you use MLR (but I could be wrong). This would seem to be supported by the fact that the Vuong test does not assume either model to be correct, which is similar to the reason why one would use robust SEs in the first place. Also, sort of related, I found the paper below to be a helpful overview:

https://www.tandfonline.com/doi/abs/10.1080/10705511.2013.824793

**Comment by isaactpetersen** [comment]
That makes sense, and thanks very much for clarifying! I also appreciate the reference. Thanks again for your work in developing this useful package.
